import fs from "node:fs/promises";
import path from "node:path";
import type { RuntimeProvisioner, InstallTeamParams, InstallAction } from "./base.js";
import { renderBootstrapFiles } from "../renderer.js";

export class CodexProvisioner implements RuntimeProvisioner {
  readonly runtime = "codex" as const;

  async installTeam(params: InstallTeamParams): Promise<void> {
    for (const agent of params.agents) {
      await fs.mkdir(agent.workspaceDir, { recursive: true });

      const allMembers = params.agents.map((a) => ({ member: a.member, agent: a.agentDef }));
      const files = renderBootstrapFiles(agent.agentDef, params.teamDef, agent.member, allMembers);

      // AGENTS.md is the primary prompt for Codex
      const agentsMd = buildAgentsMd(files, agent.agentDef.id);
      await fs.writeFile(path.join(agent.workspaceDir, "AGENTS.md"), agentsMd, "utf-8");

      for (const [name, content] of Object.entries(files)) {
        await fs.writeFile(path.join(agent.workspaceDir, name), content, "utf-8");
      }
    }
  }

  async uninstallTeam(_projectId: string, _teamId: string, workspaceRoot: string, agentIds?: string[]): Promise<void> {
    if (agentIds) {
      for (const id of agentIds) await fs.rm(path.join(workspaceRoot, id), { recursive: true, force: true });
    } else {
      await fs.rm(workspaceRoot, { recursive: true, force: true });
    }
  }

  async planInstallTeam(params: InstallTeamParams): Promise<InstallAction[]> {
    return params.agents.flatMap((a) => [
      { type: "create_workspace" as const, path: a.workspaceDir, description: `Create workspace for ${a.agentDef.id}` },
      { type: "write_file" as const, path: path.join(a.workspaceDir, "AGENTS.md"), description: `Write AGENTS.md for ${a.agentDef.id}` },
    ]);
  }
}

function buildAgentsMd(files: Record<string, string>, agentId: string): string {
  const sections: string[] = [`# Agent: ${agentId}\n`, `> Auto-generated by malaclaw. Do not edit manually.\n`];
  if (files["SOUL.md"]) sections.push(`## Persona\n\n${files["SOUL.md"]}`);
  if (files["IDENTITY.md"]) sections.push(`## Identity\n\n${files["IDENTITY.md"]}`);
  if (files["TOOLS.md"]) sections.push(`## Tools\n\n${files["TOOLS.md"]}`);
  if (files["AGENTS.md"]) sections.push(`## Team\n\n${files["AGENTS.md"]}`);
  return sections.join("\n---\n\n");
}
